// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tidbcloud/terraform-provider-tidbcloud/tidbcloud (interfaces: TiDBCloudClient)

// Package mock_client is a generated GoMock package.
package mock_client

import (
	os "os"
	reflect "reflect"

	backup "github.com/c4pt0r/go-tidbcloud-sdk-v1/client/backup"
	cluster "github.com/c4pt0r/go-tidbcloud-sdk-v1/client/cluster"
	project "github.com/c4pt0r/go-tidbcloud-sdk-v1/client/project"
	restore "github.com/c4pt0r/go-tidbcloud-sdk-v1/client/restore"
	gomock "github.com/golang/mock/gomock"
	import_service "github.com/tidbcloud/terraform-provider-tidbcloud/pkg/import/client/import_service"
)

// MockTiDBCloudClient is a mock of TiDBCloudClient interface.
type MockTiDBCloudClient struct {
	ctrl     *gomock.Controller
	recorder *MockTiDBCloudClientMockRecorder
}

// MockTiDBCloudClientMockRecorder is the mock recorder for MockTiDBCloudClient.
type MockTiDBCloudClientMockRecorder struct {
	mock *MockTiDBCloudClient
}

// NewMockTiDBCloudClient creates a new mock instance.
func NewMockTiDBCloudClient(ctrl *gomock.Controller) *MockTiDBCloudClient {
	mock := &MockTiDBCloudClient{ctrl: ctrl}
	mock.recorder = &MockTiDBCloudClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTiDBCloudClient) EXPECT() *MockTiDBCloudClientMockRecorder {
	return m.recorder
}

// CancelImport mocks base method.
func (m *MockTiDBCloudClient) CancelImport(arg0 *import_service.CancelImportParams, arg1 ...import_service.ClientOption) (*import_service.CancelImportOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelImport", varargs...)
	ret0, _ := ret[0].(*import_service.CancelImportOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelImport indicates an expected call of CancelImport.
func (mr *MockTiDBCloudClientMockRecorder) CancelImport(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelImport", reflect.TypeOf((*MockTiDBCloudClient)(nil).CancelImport), varargs...)
}

// CreateBackup mocks base method.
func (m *MockTiDBCloudClient) CreateBackup(arg0 *backup.CreateBackupParams, arg1 ...backup.ClientOption) (*backup.CreateBackupOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateBackup", varargs...)
	ret0, _ := ret[0].(*backup.CreateBackupOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBackup indicates an expected call of CreateBackup.
func (mr *MockTiDBCloudClientMockRecorder) CreateBackup(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBackup", reflect.TypeOf((*MockTiDBCloudClient)(nil).CreateBackup), varargs...)
}

// CreateCluster mocks base method.
func (m *MockTiDBCloudClient) CreateCluster(arg0 *cluster.CreateClusterParams, arg1 ...cluster.ClientOption) (*cluster.CreateClusterOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateCluster", varargs...)
	ret0, _ := ret[0].(*cluster.CreateClusterOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCluster indicates an expected call of CreateCluster.
func (mr *MockTiDBCloudClientMockRecorder) CreateCluster(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCluster", reflect.TypeOf((*MockTiDBCloudClient)(nil).CreateCluster), varargs...)
}

// CreateImport mocks base method.
func (m *MockTiDBCloudClient) CreateImport(arg0 *import_service.CreateImportParams, arg1 ...import_service.ClientOption) (*import_service.CreateImportOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateImport", varargs...)
	ret0, _ := ret[0].(*import_service.CreateImportOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateImport indicates an expected call of CreateImport.
func (mr *MockTiDBCloudClientMockRecorder) CreateImport(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateImport", reflect.TypeOf((*MockTiDBCloudClient)(nil).CreateImport), varargs...)
}

// CreateRestoreTask mocks base method.
func (m *MockTiDBCloudClient) CreateRestoreTask(arg0 *restore.CreateRestoreTaskParams, arg1 ...restore.ClientOption) (*restore.CreateRestoreTaskOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateRestoreTask", varargs...)
	ret0, _ := ret[0].(*restore.CreateRestoreTaskOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRestoreTask indicates an expected call of CreateRestoreTask.
func (mr *MockTiDBCloudClientMockRecorder) CreateRestoreTask(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRestoreTask", reflect.TypeOf((*MockTiDBCloudClient)(nil).CreateRestoreTask), varargs...)
}

// DeleteBackup mocks base method.
func (m *MockTiDBCloudClient) DeleteBackup(arg0 *backup.DeleteBackupParams, arg1 ...backup.ClientOption) (*backup.DeleteBackupOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBackup", varargs...)
	ret0, _ := ret[0].(*backup.DeleteBackupOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBackup indicates an expected call of DeleteBackup.
func (mr *MockTiDBCloudClientMockRecorder) DeleteBackup(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBackup", reflect.TypeOf((*MockTiDBCloudClient)(nil).DeleteBackup), varargs...)
}

// DeleteCluster mocks base method.
func (m *MockTiDBCloudClient) DeleteCluster(arg0 *cluster.DeleteClusterParams, arg1 ...cluster.ClientOption) (*cluster.DeleteClusterOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteCluster", varargs...)
	ret0, _ := ret[0].(*cluster.DeleteClusterOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCluster indicates an expected call of DeleteCluster.
func (mr *MockTiDBCloudClientMockRecorder) DeleteCluster(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCluster", reflect.TypeOf((*MockTiDBCloudClient)(nil).DeleteCluster), varargs...)
}

// GenerateUploadURL mocks base method.
func (m *MockTiDBCloudClient) GenerateUploadURL(arg0 *import_service.GenerateUploadURLParams, arg1 ...import_service.ClientOption) (*import_service.GenerateUploadURLOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GenerateUploadURL", varargs...)
	ret0, _ := ret[0].(*import_service.GenerateUploadURLOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateUploadURL indicates an expected call of GenerateUploadURL.
func (mr *MockTiDBCloudClientMockRecorder) GenerateUploadURL(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateUploadURL", reflect.TypeOf((*MockTiDBCloudClient)(nil).GenerateUploadURL), varargs...)
}

// GetBackupOfCluster mocks base method.
func (m *MockTiDBCloudClient) GetBackupOfCluster(arg0 *backup.GetBackupOfClusterParams, arg1 ...backup.ClientOption) (*backup.GetBackupOfClusterOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBackupOfCluster", varargs...)
	ret0, _ := ret[0].(*backup.GetBackupOfClusterOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackupOfCluster indicates an expected call of GetBackupOfCluster.
func (mr *MockTiDBCloudClientMockRecorder) GetBackupOfCluster(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackupOfCluster", reflect.TypeOf((*MockTiDBCloudClient)(nil).GetBackupOfCluster), varargs...)
}

// GetCluster mocks base method.
func (m *MockTiDBCloudClient) GetCluster(arg0 *cluster.GetClusterParams, arg1 ...cluster.ClientOption) (*cluster.GetClusterOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCluster", varargs...)
	ret0, _ := ret[0].(*cluster.GetClusterOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCluster indicates an expected call of GetCluster.
func (mr *MockTiDBCloudClientMockRecorder) GetCluster(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCluster", reflect.TypeOf((*MockTiDBCloudClient)(nil).GetCluster), varargs...)
}

// GetImport mocks base method.
func (m *MockTiDBCloudClient) GetImport(arg0 *import_service.GetImportParams, arg1 ...import_service.ClientOption) (*import_service.GetImportOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetImport", varargs...)
	ret0, _ := ret[0].(*import_service.GetImportOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImport indicates an expected call of GetImport.
func (mr *MockTiDBCloudClientMockRecorder) GetImport(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImport", reflect.TypeOf((*MockTiDBCloudClient)(nil).GetImport), varargs...)
}

// GetRestoreTask mocks base method.
func (m *MockTiDBCloudClient) GetRestoreTask(arg0 *restore.GetRestoreTaskParams, arg1 ...restore.ClientOption) (*restore.GetRestoreTaskOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRestoreTask", varargs...)
	ret0, _ := ret[0].(*restore.GetRestoreTaskOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestoreTask indicates an expected call of GetRestoreTask.
func (mr *MockTiDBCloudClientMockRecorder) GetRestoreTask(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestoreTask", reflect.TypeOf((*MockTiDBCloudClient)(nil).GetRestoreTask), varargs...)
}

// ListBackUpOfCluster mocks base method.
func (m *MockTiDBCloudClient) ListBackUpOfCluster(arg0 *backup.ListBackUpOfClusterParams, arg1 ...backup.ClientOption) (*backup.ListBackUpOfClusterOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListBackUpOfCluster", varargs...)
	ret0, _ := ret[0].(*backup.ListBackUpOfClusterOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBackUpOfCluster indicates an expected call of ListBackUpOfCluster.
func (mr *MockTiDBCloudClientMockRecorder) ListBackUpOfCluster(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackUpOfCluster", reflect.TypeOf((*MockTiDBCloudClient)(nil).ListBackUpOfCluster), varargs...)
}

// ListClustersOfProject mocks base method.
func (m *MockTiDBCloudClient) ListClustersOfProject(arg0 *cluster.ListClustersOfProjectParams, arg1 ...cluster.ClientOption) (*cluster.ListClustersOfProjectOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListClustersOfProject", varargs...)
	ret0, _ := ret[0].(*cluster.ListClustersOfProjectOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClustersOfProject indicates an expected call of ListClustersOfProject.
func (mr *MockTiDBCloudClientMockRecorder) ListClustersOfProject(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClustersOfProject", reflect.TypeOf((*MockTiDBCloudClient)(nil).ListClustersOfProject), varargs...)
}

// ListImports mocks base method.
func (m *MockTiDBCloudClient) ListImports(arg0 *import_service.ListImportsParams, arg1 ...import_service.ClientOption) (*import_service.ListImportsOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListImports", varargs...)
	ret0, _ := ret[0].(*import_service.ListImportsOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListImports indicates an expected call of ListImports.
func (mr *MockTiDBCloudClientMockRecorder) ListImports(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImports", reflect.TypeOf((*MockTiDBCloudClient)(nil).ListImports), varargs...)
}

// ListProjects mocks base method.
func (m *MockTiDBCloudClient) ListProjects(arg0 *project.ListProjectsParams, arg1 ...project.ClientOption) (*project.ListProjectsOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListProjects", varargs...)
	ret0, _ := ret[0].(*project.ListProjectsOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockTiDBCloudClientMockRecorder) ListProjects(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockTiDBCloudClient)(nil).ListProjects), varargs...)
}

// ListProviderRegions mocks base method.
func (m *MockTiDBCloudClient) ListProviderRegions(arg0 *cluster.ListProviderRegionsParams, arg1 ...cluster.ClientOption) (*cluster.ListProviderRegionsOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListProviderRegions", varargs...)
	ret0, _ := ret[0].(*cluster.ListProviderRegionsOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProviderRegions indicates an expected call of ListProviderRegions.
func (mr *MockTiDBCloudClientMockRecorder) ListProviderRegions(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProviderRegions", reflect.TypeOf((*MockTiDBCloudClient)(nil).ListProviderRegions), varargs...)
}

// ListRestoreTasks mocks base method.
func (m *MockTiDBCloudClient) ListRestoreTasks(arg0 *restore.ListRestoreTasksParams, arg1 ...restore.ClientOption) (*restore.ListRestoreTasksOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListRestoreTasks", varargs...)
	ret0, _ := ret[0].(*restore.ListRestoreTasksOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRestoreTasks indicates an expected call of ListRestoreTasks.
func (mr *MockTiDBCloudClientMockRecorder) ListRestoreTasks(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRestoreTasks", reflect.TypeOf((*MockTiDBCloudClient)(nil).ListRestoreTasks), varargs...)
}

// PreSignedUrlUpload mocks base method.
func (m *MockTiDBCloudClient) PreSignedUrlUpload(arg0 *string, arg1 *os.File, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreSignedUrlUpload", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PreSignedUrlUpload indicates an expected call of PreSignedUrlUpload.
func (mr *MockTiDBCloudClientMockRecorder) PreSignedUrlUpload(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreSignedUrlUpload", reflect.TypeOf((*MockTiDBCloudClient)(nil).PreSignedUrlUpload), arg0, arg1, arg2)
}

// UpdateCluster mocks base method.
func (m *MockTiDBCloudClient) UpdateCluster(arg0 *cluster.UpdateClusterParams, arg1 ...cluster.ClientOption) (*cluster.UpdateClusterOK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateCluster", varargs...)
	ret0, _ := ret[0].(*cluster.UpdateClusterOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCluster indicates an expected call of UpdateCluster.
func (mr *MockTiDBCloudClientMockRecorder) UpdateCluster(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCluster", reflect.TypeOf((*MockTiDBCloudClient)(nil).UpdateCluster), varargs...)
}
