// Code generated by MockGen. DO NOT EDIT.
// Source: ./tidbcloud/dedicated_api_client.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dedicated "github.com/tidbcloud/tidbcloud-cli/pkg/tidbcloud/v1beta1/dedicated"
)

// MockTiDBCloudDedicatedClient is a mock of TiDBCloudDedicatedClient interface.
type MockTiDBCloudDedicatedClient struct {
	ctrl     *gomock.Controller
	recorder *MockTiDBCloudDedicatedClientMockRecorder
}

// MockTiDBCloudDedicatedClientMockRecorder is the mock recorder for MockTiDBCloudDedicatedClient.
type MockTiDBCloudDedicatedClientMockRecorder struct {
	mock *MockTiDBCloudDedicatedClient
}

// NewMockTiDBCloudDedicatedClient creates a new mock instance.
func NewMockTiDBCloudDedicatedClient(ctrl *gomock.Controller) *MockTiDBCloudDedicatedClient {
	mock := &MockTiDBCloudDedicatedClient{ctrl: ctrl}
	mock.recorder = &MockTiDBCloudDedicatedClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTiDBCloudDedicatedClient) EXPECT() *MockTiDBCloudDedicatedClientMockRecorder {
	return m.recorder
}

// ChangeClusterRootPassword mocks base method.
func (m *MockTiDBCloudDedicatedClient) ChangeClusterRootPassword(ctx context.Context, clusterId string, body *dedicated.ClusterServiceResetRootPasswordBody) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeClusterRootPassword", ctx, clusterId, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeClusterRootPassword indicates an expected call of ChangeClusterRootPassword.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) ChangeClusterRootPassword(ctx, clusterId, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeClusterRootPassword", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).ChangeClusterRootPassword), ctx, clusterId, body)
}

// CreateCluster mocks base method.
func (m *MockTiDBCloudDedicatedClient) CreateCluster(ctx context.Context, body *dedicated.TidbCloudOpenApidedicatedv1beta1Cluster) (*dedicated.TidbCloudOpenApidedicatedv1beta1Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCluster", ctx, body)
	ret0, _ := ret[0].(*dedicated.TidbCloudOpenApidedicatedv1beta1Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCluster indicates an expected call of CreateCluster.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) CreateCluster(ctx, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCluster", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).CreateCluster), ctx, body)
}

// CreateNetworkContainer mocks base method.
func (m *MockTiDBCloudDedicatedClient) CreateNetworkContainer(ctx context.Context, body *dedicated.V1beta1NetworkContainer) (*dedicated.V1beta1NetworkContainer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetworkContainer", ctx, body)
	ret0, _ := ret[0].(*dedicated.V1beta1NetworkContainer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNetworkContainer indicates an expected call of CreateNetworkContainer.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) CreateNetworkContainer(ctx, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetworkContainer", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).CreateNetworkContainer), ctx, body)
}

// CreatePrivateEndpointConnection mocks base method.
func (m *MockTiDBCloudDedicatedClient) CreatePrivateEndpointConnection(ctx context.Context, clusterId, nodeGroupId string, body *dedicated.PrivateEndpointConnectionServiceCreatePrivateEndpointConnectionRequest) (*dedicated.V1beta1PrivateEndpointConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrivateEndpointConnection", ctx, clusterId, nodeGroupId, body)
	ret0, _ := ret[0].(*dedicated.V1beta1PrivateEndpointConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePrivateEndpointConnection indicates an expected call of CreatePrivateEndpointConnection.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) CreatePrivateEndpointConnection(ctx, clusterId, nodeGroupId, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrivateEndpointConnection", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).CreatePrivateEndpointConnection), ctx, clusterId, nodeGroupId, body)
}

// CreateTiDBNodeGroup mocks base method.
func (m *MockTiDBCloudDedicatedClient) CreateTiDBNodeGroup(ctx context.Context, clusterId string, body *dedicated.Required) (*dedicated.Dedicatedv1beta1TidbNodeGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTiDBNodeGroup", ctx, clusterId, body)
	ret0, _ := ret[0].(*dedicated.Dedicatedv1beta1TidbNodeGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTiDBNodeGroup indicates an expected call of CreateTiDBNodeGroup.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) CreateTiDBNodeGroup(ctx, clusterId, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTiDBNodeGroup", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).CreateTiDBNodeGroup), ctx, clusterId, body)
}

// CreateVPCPeering mocks base method.
func (m *MockTiDBCloudDedicatedClient) CreateVPCPeering(ctx context.Context, body *dedicated.Dedicatedv1beta1VpcPeering) (*dedicated.Dedicatedv1beta1VpcPeering, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVPCPeering", ctx, body)
	ret0, _ := ret[0].(*dedicated.Dedicatedv1beta1VpcPeering)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVPCPeering indicates an expected call of CreateVPCPeering.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) CreateVPCPeering(ctx, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVPCPeering", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).CreateVPCPeering), ctx, body)
}

// DeleteCluster mocks base method.
func (m *MockTiDBCloudDedicatedClient) DeleteCluster(ctx context.Context, clusterId string) (*dedicated.TidbCloudOpenApidedicatedv1beta1Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCluster", ctx, clusterId)
	ret0, _ := ret[0].(*dedicated.TidbCloudOpenApidedicatedv1beta1Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCluster indicates an expected call of DeleteCluster.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) DeleteCluster(ctx, clusterId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCluster", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).DeleteCluster), ctx, clusterId)
}

// DeleteNetworkContainer mocks base method.
func (m *MockTiDBCloudDedicatedClient) DeleteNetworkContainer(ctx context.Context, networkContainerId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetworkContainer", ctx, networkContainerId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNetworkContainer indicates an expected call of DeleteNetworkContainer.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) DeleteNetworkContainer(ctx, networkContainerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetworkContainer", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).DeleteNetworkContainer), ctx, networkContainerId)
}

// DeletePrivateEndpointConnection mocks base method.
func (m *MockTiDBCloudDedicatedClient) DeletePrivateEndpointConnection(ctx context.Context, clusterId, nodeGroupId, privateEndpointConnectionId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrivateEndpointConnection", ctx, clusterId, nodeGroupId, privateEndpointConnectionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePrivateEndpointConnection indicates an expected call of DeletePrivateEndpointConnection.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) DeletePrivateEndpointConnection(ctx, clusterId, nodeGroupId, privateEndpointConnectionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrivateEndpointConnection", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).DeletePrivateEndpointConnection), ctx, clusterId, nodeGroupId, privateEndpointConnectionId)
}

// DeleteTiDBNodeGroup mocks base method.
func (m *MockTiDBCloudDedicatedClient) DeleteTiDBNodeGroup(ctx context.Context, clusterId, nodeGroupId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTiDBNodeGroup", ctx, clusterId, nodeGroupId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTiDBNodeGroup indicates an expected call of DeleteTiDBNodeGroup.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) DeleteTiDBNodeGroup(ctx, clusterId, nodeGroupId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTiDBNodeGroup", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).DeleteTiDBNodeGroup), ctx, clusterId, nodeGroupId)
}

// DeleteVPCPeering mocks base method.
func (m *MockTiDBCloudDedicatedClient) DeleteVPCPeering(ctx context.Context, vpcPeeringId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVPCPeering", ctx, vpcPeeringId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVPCPeering indicates an expected call of DeleteVPCPeering.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) DeleteVPCPeering(ctx, vpcPeeringId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVPCPeering", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).DeleteVPCPeering), ctx, vpcPeeringId)
}

// GetCluster mocks base method.
func (m *MockTiDBCloudDedicatedClient) GetCluster(ctx context.Context, clusterId string) (*dedicated.TidbCloudOpenApidedicatedv1beta1Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCluster", ctx, clusterId)
	ret0, _ := ret[0].(*dedicated.TidbCloudOpenApidedicatedv1beta1Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCluster indicates an expected call of GetCluster.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) GetCluster(ctx, clusterId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCluster", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).GetCluster), ctx, clusterId)
}

// GetNetworkContainer mocks base method.
func (m *MockTiDBCloudDedicatedClient) GetNetworkContainer(ctx context.Context, networkContainerId string) (*dedicated.V1beta1NetworkContainer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkContainer", ctx, networkContainerId)
	ret0, _ := ret[0].(*dedicated.V1beta1NetworkContainer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkContainer indicates an expected call of GetNetworkContainer.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) GetNetworkContainer(ctx, networkContainerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkContainer", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).GetNetworkContainer), ctx, networkContainerId)
}

// GetPrivateEndpointConnection mocks base method.
func (m *MockTiDBCloudDedicatedClient) GetPrivateEndpointConnection(ctx context.Context, clusterId, nodeGroupId, privateEndpointConnectionId string) (*dedicated.V1beta1PrivateEndpointConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateEndpointConnection", ctx, clusterId, nodeGroupId, privateEndpointConnectionId)
	ret0, _ := ret[0].(*dedicated.V1beta1PrivateEndpointConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateEndpointConnection indicates an expected call of GetPrivateEndpointConnection.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) GetPrivateEndpointConnection(ctx, clusterId, nodeGroupId, privateEndpointConnectionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateEndpointConnection", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).GetPrivateEndpointConnection), ctx, clusterId, nodeGroupId, privateEndpointConnectionId)
}

// GetRegion mocks base method.
func (m *MockTiDBCloudDedicatedClient) GetRegion(ctx context.Context, regionId string) (*dedicated.Commonv1beta1Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegion", ctx, regionId)
	ret0, _ := ret[0].(*dedicated.Commonv1beta1Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegion indicates an expected call of GetRegion.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) GetRegion(ctx, regionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegion", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).GetRegion), ctx, regionId)
}

// GetTiDBNodeGroup mocks base method.
func (m *MockTiDBCloudDedicatedClient) GetTiDBNodeGroup(ctx context.Context, clusterId, nodeGroupId string) (*dedicated.Dedicatedv1beta1TidbNodeGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTiDBNodeGroup", ctx, clusterId, nodeGroupId)
	ret0, _ := ret[0].(*dedicated.Dedicatedv1beta1TidbNodeGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTiDBNodeGroup indicates an expected call of GetTiDBNodeGroup.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) GetTiDBNodeGroup(ctx, clusterId, nodeGroupId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTiDBNodeGroup", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).GetTiDBNodeGroup), ctx, clusterId, nodeGroupId)
}

// GetVPCPeering mocks base method.
func (m *MockTiDBCloudDedicatedClient) GetVPCPeering(ctx context.Context, vpcPeeringId string) (*dedicated.Dedicatedv1beta1VpcPeering, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVPCPeering", ctx, vpcPeeringId)
	ret0, _ := ret[0].(*dedicated.Dedicatedv1beta1VpcPeering)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVPCPeering indicates an expected call of GetVPCPeering.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) GetVPCPeering(ctx, vpcPeeringId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVPCPeering", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).GetVPCPeering), ctx, vpcPeeringId)
}

// ListCloudProviders mocks base method.
func (m *MockTiDBCloudDedicatedClient) ListCloudProviders(ctx context.Context, projectId string) ([]dedicated.V1beta1RegionCloudProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCloudProviders", ctx, projectId)
	ret0, _ := ret[0].([]dedicated.V1beta1RegionCloudProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCloudProviders indicates an expected call of ListCloudProviders.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) ListCloudProviders(ctx, projectId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCloudProviders", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).ListCloudProviders), ctx, projectId)
}

// ListClusters mocks base method.
func (m *MockTiDBCloudDedicatedClient) ListClusters(ctx context.Context, projectId string, pageSize *int32, pageToken *string) (*dedicated.TidbCloudOpenApidedicatedv1beta1ListClustersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClusters", ctx, projectId, pageSize, pageToken)
	ret0, _ := ret[0].(*dedicated.TidbCloudOpenApidedicatedv1beta1ListClustersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClusters indicates an expected call of ListClusters.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) ListClusters(ctx, projectId, pageSize, pageToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClusters", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).ListClusters), ctx, projectId, pageSize, pageToken)
}

// ListNetworkContainers mocks base method.
func (m *MockTiDBCloudDedicatedClient) ListNetworkContainers(ctx context.Context, projectId string, pageSize *int32, pageToken *string) (*dedicated.V1beta1ListNetworkContainersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNetworkContainers", ctx, projectId, pageSize, pageToken)
	ret0, _ := ret[0].(*dedicated.V1beta1ListNetworkContainersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNetworkContainers indicates an expected call of ListNetworkContainers.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) ListNetworkContainers(ctx, projectId, pageSize, pageToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNetworkContainers", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).ListNetworkContainers), ctx, projectId, pageSize, pageToken)
}

// ListPrivateEndpointConnections mocks base method.
func (m *MockTiDBCloudDedicatedClient) ListPrivateEndpointConnections(ctx context.Context, clusterId, nodeGroupId string, pageSize *int32, pageToken *string) (*dedicated.V1beta1ListPrivateEndpointConnectionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPrivateEndpointConnections", ctx, clusterId, nodeGroupId, pageSize, pageToken)
	ret0, _ := ret[0].(*dedicated.V1beta1ListPrivateEndpointConnectionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPrivateEndpointConnections indicates an expected call of ListPrivateEndpointConnections.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) ListPrivateEndpointConnections(ctx, clusterId, nodeGroupId, pageSize, pageToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPrivateEndpointConnections", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).ListPrivateEndpointConnections), ctx, clusterId, nodeGroupId, pageSize, pageToken)
}

// ListRegions mocks base method.
func (m *MockTiDBCloudDedicatedClient) ListRegions(ctx context.Context, cloudProvider, projectId string) ([]dedicated.Commonv1beta1Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRegions", ctx, cloudProvider, projectId)
	ret0, _ := ret[0].([]dedicated.Commonv1beta1Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRegions indicates an expected call of ListRegions.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) ListRegions(ctx, cloudProvider, projectId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRegions", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).ListRegions), ctx, cloudProvider, projectId)
}

// ListTiDBNodeGroups mocks base method.
func (m *MockTiDBCloudDedicatedClient) ListTiDBNodeGroups(ctx context.Context, clusterId string, pageSize *int32, pageToken *string) (*dedicated.Dedicatedv1beta1ListTidbNodeGroupsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTiDBNodeGroups", ctx, clusterId, pageSize, pageToken)
	ret0, _ := ret[0].(*dedicated.Dedicatedv1beta1ListTidbNodeGroupsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTiDBNodeGroups indicates an expected call of ListTiDBNodeGroups.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) ListTiDBNodeGroups(ctx, clusterId, pageSize, pageToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTiDBNodeGroups", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).ListTiDBNodeGroups), ctx, clusterId, pageSize, pageToken)
}

// ListVPCPeerings mocks base method.
func (m *MockTiDBCloudDedicatedClient) ListVPCPeerings(ctx context.Context, projectId, cloudProvider string, pageSize *int32, pageToken *string) (*dedicated.Dedicatedv1beta1ListVpcPeeringsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVPCPeerings", ctx, projectId, cloudProvider, pageSize, pageToken)
	ret0, _ := ret[0].(*dedicated.Dedicatedv1beta1ListVpcPeeringsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVPCPeerings indicates an expected call of ListVPCPeerings.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) ListVPCPeerings(ctx, projectId, cloudProvider, pageSize, pageToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVPCPeerings", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).ListVPCPeerings), ctx, projectId, cloudProvider, pageSize, pageToken)
}

// PauseCluster mocks base method.
func (m *MockTiDBCloudDedicatedClient) PauseCluster(ctx context.Context, clusterId string) (*dedicated.TidbCloudOpenApidedicatedv1beta1Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseCluster", ctx, clusterId)
	ret0, _ := ret[0].(*dedicated.TidbCloudOpenApidedicatedv1beta1Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PauseCluster indicates an expected call of PauseCluster.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) PauseCluster(ctx, clusterId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseCluster", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).PauseCluster), ctx, clusterId)
}

// ResumeCluster mocks base method.
func (m *MockTiDBCloudDedicatedClient) ResumeCluster(ctx context.Context, clusterId string) (*dedicated.TidbCloudOpenApidedicatedv1beta1Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeCluster", ctx, clusterId)
	ret0, _ := ret[0].(*dedicated.TidbCloudOpenApidedicatedv1beta1Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeCluster indicates an expected call of ResumeCluster.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) ResumeCluster(ctx, clusterId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeCluster", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).ResumeCluster), ctx, clusterId)
}

// UpdateCluster mocks base method.
func (m *MockTiDBCloudDedicatedClient) UpdateCluster(ctx context.Context, clusterId string, body *dedicated.ClusterServiceUpdateClusterRequest) (*dedicated.TidbCloudOpenApidedicatedv1beta1Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCluster", ctx, clusterId, body)
	ret0, _ := ret[0].(*dedicated.TidbCloudOpenApidedicatedv1beta1Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCluster indicates an expected call of UpdateCluster.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) UpdateCluster(ctx, clusterId, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCluster", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).UpdateCluster), ctx, clusterId, body)
}

// UpdateTiDBNodeGroup mocks base method.
func (m *MockTiDBCloudDedicatedClient) UpdateTiDBNodeGroup(ctx context.Context, clusterId, nodeGroupId string, body *dedicated.TidbNodeGroupServiceUpdateTidbNodeGroupRequest) (*dedicated.Dedicatedv1beta1TidbNodeGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTiDBNodeGroup", ctx, clusterId, nodeGroupId, body)
	ret0, _ := ret[0].(*dedicated.Dedicatedv1beta1TidbNodeGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTiDBNodeGroup indicates an expected call of UpdateTiDBNodeGroup.
func (mr *MockTiDBCloudDedicatedClientMockRecorder) UpdateTiDBNodeGroup(ctx, clusterId, nodeGroupId, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTiDBNodeGroup", reflect.TypeOf((*MockTiDBCloudDedicatedClient)(nil).UpdateTiDBNodeGroup), ctx, clusterId, nodeGroupId, body)
}
