package provider

import (
	"context"
	"fmt"
	"math/rand"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

type dedicatedRegionsDataSourceData struct {
	Id    types.String      `tfsdk:"id"`
	Items []dedicatedRegion `tfsdk:"items"`
	Total types.Int64       `tfsdk:"total"`
}

var _ datasource.DataSource = &dedicatedRegionsDataSource{}

type dedicatedRegionsDataSource struct {
	provider *tidbcloudProvider
}

func NewDedicatedRegionsDataSource() datasource.DataSource {
	return &dedicatedRegionsDataSource{}
}

func (d *dedicatedRegionsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dedicated_regions"
}

func (d *dedicatedRegionsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	var ok bool
	if d.provider, ok = req.ProviderData.(*tidbcloudProvider); !ok {
		resp.Diagnostics.AddError("Internal provider error",
			fmt.Sprintf("Error in Configure: expected %T but got %T", tidbcloudProvider{}, req.ProviderData))
	}
}

func (d *dedicatedRegionsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "dedicated regions data source",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "data source ID",
				Computed:            true,
			},
			"items": schema.ListNestedAttribute{
				MarkdownDescription: "The items of regions",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"region_id": schema.StringAttribute{
							MarkdownDescription: "The ID of the region. It is generated by TiDB Cloud.",
							Computed:            true,
						},
						"cloud_provider": schema.StringAttribute{
							MarkdownDescription: "The cloud provider of the region.",
							Computed:            true,
						},
						"display_name": schema.StringAttribute{
							MarkdownDescription: "The display name of the region.",
							Computed:            true,
						},
					},
				},
			},
			"total": schema.Int64Attribute{
				MarkdownDescription: "The total number of regions in the project.",
				Computed:            true,
			},
		},
	}
}

func (d *dedicatedRegionsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data dedicatedRegionsDataSourceData
	diags := req.Config.Get(ctx, &data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Trace(ctx, "read regions data source")
	regions, err := d.provider.DedicatedClient.ListRegions(ctx)
	if err != nil {
		resp.Diagnostics.AddError("Read Error", fmt.Sprintf("Unable to call ListRegions, got error: %s", err))
		return
	}

	data.Id = types.StringValue(strconv.FormatInt(rand.Int63(), 10))
	data.Total = types.Int64Value(int64(*regions.TotalSize))
	var items []dedicatedRegion
	for _, key := range regions.Regions {
		items = append(items, dedicatedRegion{
			RegionId:      types.StringValue(*key.RegionId),
			CloudProvider: types.StringValue(string(*key.CloudProvider)),
			DisplayName:   types.StringValue(*key.DisplayName),
		})
	}
	data.Items = items

	diags = resp.State.Set(ctx, &data)
	resp.Diagnostics.Append(diags...)
}
